### ISSUE TITLE
Undefined variable 'time'

### ISSUE THREAD

**Issue by qcrafter** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#1]
Undefined variable 'time'
![image](https://user-images.githubusercontent.com/74731706/100026620-6d584d00-2deb-11eb-9a2c-44209eeaaf19.png)

**Comment by NoNameoN-A** [comment]
Having developed the various loops in different parts I forgot to remove 'time', just delete it everywhere or re-download the file.
I just edited it :)

!Don't delete 'time' on line 5
