### ISSUE TITLE
tiktok-views-follow-heart-bot wont open

### ISSUE THREAD

**Issue by jazxminemasters** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#10]
hello sorry ik this is probably annoying bc i dont know how to use this but the tiktok-views-follow-heart-bot wont open what do i do ?

**Comment by NoNameoN-A** [comment]
If you followed my guide and you didn't solve I don't know how help you

**Comment by jazxminemasters** [comment]
> If you followed my guide and you didn't solve I don't know how can I help you

okay sorry

**Comment by glossyweb** [comment]
donain vipto.de die already, have a redirect to new domain. And now just 500 views, adn so slowly
