### ISSUE TITLE
[ERROR] A generic error occurred. Now will retry again

### ISSUE THREAD

**Issue by Prottoy2938** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#100]
If I choose `1. Auto Views (500)`, everything works as expected.

But if I choose anything other than that, like `2. Auto hearts`, `4. Auto comments` etc, it shows this error:
> A generic error occurred. Now will retry again

This happens every time.

I followed the instructions and didn't change the code

**Comment by NoNameoN-A** [comment]
probably it is for the platform so it isn't for my bot, can you do this without the bot on the website?

**Comment by Prottoy2938** [comment]
no

**Comment by NoNameoN-A** [comment]
ok so I can't help you because it depends on the website when it is available on the website it will works with the bot
