### ISSUE TITLE
[BUG] VIPTO.DE is 502

### ISSUE THREAD

**Issue by powderblock** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#11]
When running the program, vipto.de is 502 bad gateway.

See attached screenshot.

Steps to reproduce: Run the app .py with a URL and selenium webdriver. Wait for the page to "load" and see the 502 error. :(
Very sad please fix.
![vip de down](https://user-images.githubusercontent.com/1458607/101515604-86651000-394c-11eb-8ed3-25ccf3e6a3c8.PNG)

**Comment by powderblock** [comment]
Not sure if this is my end or vipto.de side. Is there an alternative we can use to this .de website?

**Comment by NoNameoN-A** [comment]
Did you active a vpn? Your must close it...
If it doesn't work try to change your IPv4 addresses with 8.8.8.8; 8.8.4.4;

[Guide link](https://developers.google.com/speed/public-dns/docs/using) or search on Google How to change public dns

Doesn't exist an another website like it for now
