### ISSUE TITLE
Error 502 Bad Gateway

### ISSUE THREAD

**Issue by NoobierNoob** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#12]
name: Error 502 Bad Gateway on vipto.de
about: When I launch the program, it pulls up the web page, but when it loads into https://vipto.de/, it throws a Error 502 message.
title: "Error 502 Bad Gateway"
labels: bug
assignees: NoNameoN-A

---

**Describe the bug**
When I launch the program, it pulls up the web page, but when it loads into https://vipto.de/, it throws a Error 502

**To Reproduce**
1. Go to command prompt
2. CD into folder containing the .py script
3. run script using command give on your page
4. When opens window onto https://vipto.de/ gives Error 502

**Expected behavior**
I expect the captcha to show up on the page.

**Screenshots**
https://gyazo.com/de31c6607004fc34d17cfbb091645d18.

**Info**
Chrome and ChromeDriver Version
Chrome: 87.0.4280.88
ChromeDriver: 87.0.4280.88

**Additional context**

**Comment by NoobierNoob** [comment]
Read other error 502 issues, changed IPv4 addresses to 8.8.8.8; 8.8.4.4 and still no success

**Comment by NoobierNoob** [comment]
Looks like I fixed it. I added
chrome_options.add_experimental_option("mobileEmulation", mobile_emulation) and mobile_emulation = { "deviceName": "Nexus 5" }
into the chrome_options area in the python file

**Comment by adriyunn** [comment]
how do i fix tihs 
` File "C:\Users\ADMIN\OneDrive\Desktop\TikTok-Follow-Heart-Views-Bot-main\bot.py", line 162
    mobile_emulation = { "deviceName": "Nexus 5" }) #Change it
    ^
SyntaxError: positional argument follows keyword argument`
