### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by ubed354311** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#17]
sleep(10)
TabError: inconsistent use of tabs and spaces in indentation

**Comment by NoNameoN-A** [comment]
what is the row?

**Comment by Stijnman** [comment]
Hi, I have the same error I think:
File "C:\Users\Stijnman\Desktop\TikTok-Follow-Heart-Views-Bot-main\TikTok-Views-Follow-Heart-Bot.py", line 33
    sleep(10)
TabError: inconsistent use of tabs and spaces in indentation

**Comment by ubed354311** [comment]
> what is the row?

File "C:\Users\Asus\Downloads\TikTok-Follow-Heart-Views-Bot-main\TikTok-Follow-Heart-Views-Bot-main\TikTok-Follow-Heart-Views-Bot-main.py", line 33
    sleep(10)
TabError: inconsistent use of tabs and spaces in indentation

**Comment by NoNameoN-A** [comment]
I controlled now and it is correct... however i will upload again the file

**Comment by ubed354311** [comment]
> I controlled now and it is correct... however i will upload again the file

thnks my brother

**Comment by Lxgisch** [comment]
Hey, I still have this issue. I downloaded the new file but I get the same message. Is this on mine side or did I download the wrong file?

**Comment by NoNameoN-A** [comment]
send me this file with your email at alessandrogreco@hacari.org

**Comment by NoNameoN-A** [comment]
@ubed354311 did you solve?
Can i close the issue?

**Comment by ubed354311** [comment]
> @ubed354311 did you solve?
> Can i close the issue?

no bro
I haven't solved the problem yet

**Comment by SebastianBeerg** [comment]
I'm Having the same problem!

**Comment by NoNameoN-A** [comment]
@ubed354311 @SebastianBeerg @Lxgisch @Stijnman I update a new version of the file, try now using this file.
[README section](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot#taberror-inconsistent-use-of-tabs-and-spaces-in-indentation)

### Please, say me if you solve or not

**Comment by Stijnman** [comment]
@NoNameoN-A  Thank you, this works!. All I had to do was change the path for the driver = webdriver.Chrome('C:/Users/User/Desktop/TikTok-Follow-Heart-Views-Bot-main/chromedriver.exe',chrome_options=chrome_options).

It all works but I get a few warnings: 

C:\Users\User\Desktop\TikTok-Follow-Heart-Views-Bot-main\Bot_For_Bugged.py:13: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome('C:/Users/User/Desktop/TikTok-Follow-Heart-Views-Bot-main/chromedriver.exe',chrome_options=chrome_options)

Views success delivered! Total 500 views
Views success delivered! Total 1000 views
[10900:9080:1227/133236.375:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
[10900:9080:1227/133236.425:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
Views success delivered! Total 1500 views

**Comment by NoNameoN-A** [comment]
ok good... so now your error line is `[10900:9080:1227/133236.375:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101` but it works correctly?
If you see your tiktok video it have more views? @Stijnman

**Comment by Stijnman** [comment]
Yes sir that's correct. It's working perfect, views get added

**Comment by NoNameoN-A** [comment]
ok, good :D 
Your is a strange error because you should not see that, but you should see a simple error string like `An error occured. Now will retry again`... however it works, so happy new year to everybody :D

**Comment by imx16** [comment]
sleep(10)
TabError: inconsistent use of tabs and spaces in indentation

same error on line 33

**Comment by Stijnman** [comment]
@imx16 Try the version @NoNameoN-A  created to solve the problem ... Look in the homepage for Bot_For_Bugged.py

**Comment by NoNameoN-A** [comment]
@imx16 -> https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot#taberror-inconsistent-use-of-tabs-and-spaces-in-indentation

**Comment by Krxzy** [comment]
I keep getting the same error, Even if I use the bugged py still same thing. Any help?

**Comment by NoNameoN-A** [comment]
@Krxzy send me a photo pls

**Comment by Diamadi11** [comment]
Hi I have this error: C:\Users\NitroPC\Desktop\TikTok-Follow-Heart-Views-Bot-main>py Bot.py
  File "C:\Users\NitroPC\Desktop\TikTok-Follow-Heart-Views-Bot-main\Bot.py", line 26
    sleep(10)
TabError: inconsistent use of tabs and spaces in indentation
 Download the file you left and it still does not work.

**Comment by NoNameoN-A** [comment]
IF YOU HAVE TAB ERROR RE-DOWNLOAD NOW AND USE => Bot_For_Bugged.py

**Comment by Diamadi11** [comment]
Traceback (most recent call last):
  File "C:\Users\NitroPC\Desktop\TikTok-Follow-Heart-Views-Bot-main\Bot_For_Bugged.py", line 128, in <module>
    vidUrl = raw_input("Insert your TikTok link: ")
NameError: name 'raw_input' is not defined

now I get this error

**Comment by NoNameoN-A** [comment]
> Traceback (most recent call last):
> File "C:\Users\NitroPC\Desktop\TikTok-Follow-Heart-Views-Bot-main\Bot_For_Bugged.py", line 128, in
> vidUrl = raw_input("Insert your TikTok link: ")
> NameError: name 'raw_input' is not defined
> 
> now I get this error

Change line 132 with this `vidUrl = input(r"Insert your TikTok link: ")`

**Comment by justanothertiktokman** [comment]
Hi, im getting this error:

SyntaxError: unexpected character after line continuation character

It's in line 136 btw

**Comment by NoNameoN-A** [comment]
# VIDEO FOR BEGINNERS - Windows aviable
If you are a beginners release a star this repository, follow me and send me a screenshot on the email alessandrogreco@hacari.org, i will send you a video where i'll show you what you must to do for solve the errors and for make it work

[Email](mailto:alessandrogreco@hacari.org)
[Repository](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot#video-for-beginners---windows-aviable)
