### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation after updated file[BUG]

### ISSUE THREAD

**Issue by Lxgisch** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#18]
Hey I downloaded the updated file but i still get the error message:
line 33
sleep(10)
TabError: inconsistent use of tabs and spaces in indentation

Does It still dont work or did I download the wrong file?

**Comment by NoNameoN-A** [comment]
the tabulation error was not present before and is not present now, I tried it on my computer and it is strange that this thing happens.  As I already told you, please send me your file to my email address so I can check it.  I can not do anything else.
Good day :)
