### ISSUE TITLE
Bot wont open Chrome Webbrowser

### ISSUE THREAD

**Issue by kaiyaf57** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#2]
Python and all dependencies are installed without errors.
However, the bot does not open the Chrome web browser instance. 
I have tested different versions of the latest Chrome Webdriver releases, also without positive result. 

ChromeDriver 85.0.4183.87 ...doesnt work for me 
ChromeDriver 86.0.4240.22 ...doesnt work for me 
ChromeDriver 87.0.4280.20 ...doesnt work for me 
ChromeDriver 84.0.4147.30 ...doesnt work for me

**Comment by NoNameoN-A** [comment]
I have shared the code for help everybody. Is possible that some else 
body have your same problem so if you create an issue on "issues 
sections" you can help me to help you (:

Issues section: 
https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot/issues

**Comment by NoNameoN-A** [comment]
Do you have installed Google Chrome? What is the GoogleChrome version?

If you don't know how find this info you can open Google Chrome go to Settings so click ok About Chrome and you can see some thing like `Version 87.0.4280.66 (Official Build) (64-bit)`

You must download ChromeDriver equals your GoogleChrome version, so for me is `ChromeDriver 87.0.4280.20`

Say me if you solve

**Comment by Esionru** [comment]
check line 12

**Comment by NoNameoN-A** [comment]
Sure @Esionru .
@kaiyaf57 You must change this line
`driver = webdriver.Chrome('/home/nonameon/Documents/chromedriver',chrome_options=chrome_options)`
With your path, so, if your path is something like `/home/kaiyaf/Desktop/chromedriver` you must change with this, end, if you are on Windows you must insert the `.exe`
