### ISSUE TITLE
Сhrome Options deprecated and more problems

### ISSUE THREAD

**Issue by Redas17** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#20]
Hello, for 2 days trying to make bot work (because it's great I think) ))) Now "chrome_options" deprecated, and I get error stating that, I changed "chrome_options" to "options", now I get different error. Please help me to fix this, THANK YOU FRIEND!

PS - I have chrome, pip, selenium, chrome driver and etc.

Traceback (most recent call last):
  File "C:\Users\REDAS\AppData\Local\Programs\Python\Python38\lib\site-packages\
selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\REDAS\AppData\Local\Programs\Python\Python38\lib\subprocess.py"
, line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\REDAS\AppData\Local\Programs\Python\Python38\lib\subprocess.py"
, line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\REDAS\Desktop\TikTok-Follow-Heart-Views-Bot-main\Bot_For_Bugged
.py", line 13, in <module>
    driver = webdriver.Chrome('/home/nonameon/Documenti/Coding/chromedriver',opt
ions=options)
  File "C:\Users\REDAS\AppData\Local\Programs\Python\Python38\lib\site-packages\
selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\REDAS\AppData\Local\Programs\Python\Python38\lib\site-packages\
selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executabl
e needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chrome
driver/home

**Comment by NoNameoN-A** [comment]
Did you change 13° line?
Send me it

**Comment by NoNameoN-A** [comment]
In your error lines you have this
`line 13, in driver = webdriver.Chrome('/home/nonameon/Documenti/Coding/chromedriver'`

So you didn't change it.
You must insert your chromedriver path and in you use Windows remember to under the .exe

### Say me if you solve 😁

**Comment by Zaydo123** [comment]
driver = webdriver.Chrome('/home/nonameon/Documenti/Coding/chromedriver',opt
ions=options)

as long as chromedriver.exe is in the same location/folder as the script, you should be able to ignore the path entirely.

Ex: driver = webdriver.Chrome(opt
ions=options)

It will automatically find chrome driver as long as it's in the same folder

**Comment by Redas17** [comment]
I've put chromedriver.exe in the same folder, and it works now. I thought it would auto follow and unfollow, but it does something different, but useful))

**Comment by Zaydo123** [comment]
> I've put chromedriver.exe in the same folder, and it works now. I thought it would auto follow and unfollow, but it does something different, but useful)) 

Yeah no problem. Right now followers and hearts don't work, but it should be fixed in a couple days.

**Comment by Redas17** [comment]
> > I've put chromedriver.exe in the same folder, and it works now. I thought it would auto follow and unfollow, but it does something different, but useful))
> 
> Yeah no problem. Right now followers and hearts don't work, but it should be fixed in a couple days.

Did it ever worked? I am new on TikTok, and it feels for me, that views don't make any good for account boost, or I miss something.

Want to mention for future that I changed

driver = webdriver.Chrome('/home/nonameon/Documenti/Coding/chromedriver',opt
ions=options)

to

driver = webdriver.Chrome(opt
ions=options)

**Comment by Zaydo123** [comment]
To be honest artificial views, likes, and stuff don't actually help real people to find you, but they just look cool as big numbers.

But yea the likes and stuff was working a few days ago I think
