### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by h0r** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#23]
Any idea how to fix this error? 
![err](https://user-images.githubusercontent.com/75509924/103729420-673eba00-4fae-11eb-9343-87758e760cd9.png)

**Comment by Zaydo123** [comment]
In command prompt try running "pip install pyfiglet"

**Comment by h0r** [comment]
Yeah I figured, I ran pip install pyfiglet==0.7 though. This is the error I'm having now:
![image](https://user-images.githubusercontent.com/75509924/103729836-4d51a700-4faf-11eb-8360-09cdd33e5c3f.png)

**Comment by Zaydo123** [comment]
Try running the install without the == part. I don't know if it will work with your version of python.

**Comment by h0r** [comment]
![image](https://user-images.githubusercontent.com/75509924/103730144-17f98900-4fb0-11eb-9896-76e64b821728.png)

**Comment by Zaydo123** [comment]
did you by any chance mess with the code? it should say "options = options" . If you'd like, send me the code you're running right now and I can make it a little more bug free.

**Comment by h0r** [comment]
Tried running with all the "driver =" possibilities you've given and it throws the same error.

**Comment by h0r** [comment]
I thought you told me to try "options == options" ?

**Comment by Zaydo123** [comment]
send me ur code, i'll correct it all.

**Comment by h0r** [comment]
`
from selenium import webdriver
from selenium.webdriver.support.ui import Select
import pyfiglet
from os import system
from time import sleep
import sys

chrome_options = webdriver.ChromeOptions()
#chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('/home/nonameon/Documenti/Coding/chromedriver',options=options)

i = 0

def loop1():
    global i
    sleep(10)
    try:
        driver.find_element_by_xpath("/html/body/div[4]/div[1]/div[3]/div/div[4]/div/button").click()
    except:
        print("You didn't solve the captcha yet. Need to refresh to avoid endless loop.")
        driver.refresh()
        loop1()
    try:
        sleep(2)
        driver.find_element_by_xpath("//*[@id=\"sid4\"]/div/div/div/form/div/input").send_keys(vidUrl)
        sleep(1)
        driver.find_element_by_xpath("//*[@id=\"sid4\"]/div/div/div/form/div/div/button").click()
        sleep(2)
        driver.find_element_by_xpath("//*[@id=\"c2VuZC9mb2xsb3dlcnNfdGlrdG9V\"]/div[1]/div/form/button").click()
        sleep(10)
        driver.refresh()
        i += 1
        total = i * 500
        print("Views success delivered! Total", total,"views")
        sleep(80)
        loop1()
    except:
        print("An error occured. Now will retry again")
        driver.refresh()
        sleep(20)
        loop1()

def loop2():
    sleep(10)
    try:
        driver.find_element_by_xpath("/html/body/div[4]/div[1]/div[3]/div/div[2]/div/button").click()
    except:
        print("You didn't solve the captcha yet. Need to refresh to avoid endless loop.")
        driver.refresh()
        loop2()
    try:
        sleep(2)
        driver.find_element_by_xpath("/html/body/div[4]/div[3]/div/div/div/form/div/input").send_keys(vidUrl)
        sleep(1)
        driver.find_element_by_xpath("/html/body/div[4]/div[3]/div/div/div/form/div/div/button").click()
        sleep(10)
        driver.find_element_by_xpath("/html/body/div[4]/div[3]/div/div/div/div/div[1]/div/form/button").click()
        sleep(10)
        hearts = driver.find_element_by_xpath('//*[@id="c2VuZE9nb2xsb3dlcnNfdGlrdG9r"]/span').text
        sleep(55)
        print(hearts," Success delivered!")
        sleep(100)
        driver.refresh()
        sleep(200)
        loop2()
    except:
        print("An error occured. Now will retry again")
        driver.refresh()
        sleep(355)
        loop2()

def loop3():
    sleep(10)
    try:
        driver.find_element_by_xpath("/html/body/div[4]/div[1]/div[3]/div/div[3]/div/button").click()
    except:
        print("You didn't solve the captcha yet. Need to refresh to avoid endless loop.")
        driver.refresh()
        loop2()
    try:
        sleep(2)
        driver.find_element_by_xpath("/html/body/div[4]/div[4]/div/div/div/form/div/input").send_keys(vidUrl)
        sleep(1)
        driver.find_element_by_xpath("/html/body/div[4]/div[4]/div/div/div/form/div/div/button").click()
        sleep(5)
        driver.find_element_by_xpath("/html/body/div[4]/div[4]/div/div/div/div/div[1]/div/form/button").click()
        sleep(5)
        driver.find_element_by_xpath("/html/body/div[4]/div[4]/div/div/div/div/form/ul/li/div/button").click()
        sleep(47)
        driver.refresh()
        loop3()
    except:
        print("An error occured. Now will retry again")
        driver.refresh()
        sleep(50)
        loop3()

def loop4():
    sleep(20)
    wait_time = 660 #11 minutes
    try:
        driver.find_element_by_xpath("/html/body/div[4]/div[1]/div[3]/div/div[1]/div/button").click() #Followers
    except:
        print("You didn't solve the captcha yet. Need to refresh to avoid endless loop.")
        driver.refresh()
        loop4()
    try:
        sleep(20)
        driver.find_element_by_xpath("/html/body/div[4]/div[2]/div/div/div/form/div/input").send_keys(vidUrl) #Write
        sleep(2)
        driver.find_element_by_xpath("//*[@id=\"sid\"]/div/div/div/form/div/div/button").click() #Search
        sleep(20)
        driver.find_element_by_xpath("//*[@id=\"c2VuZF9mb2xsb3dlcnNfdGlrdG9r\"]/div[1]/div/form/button").click() #AddFollowers
        sleep(wait_time/3)
        print("Success delivered")
        sleep(wait_time/3)
        driver.refresh()
        sleep(wait_time/3)
        loop4()
    except:
        print("Oops!", sys.exc_info()[0], "occurred.")
        print("An error occurred. Now will retry again")
        driver.refresh()
        sleep(wait_time)
        loop4()

vidUrl = "https://www.tiktok.com/@antidreamgang/video/6913604502931180806" #Change with one of your tiktok videos

system("clear") #If you have Windows you can use cls
tiktokbot = pyfiglet.figlet_format("NoNameoN", font="slant")
print(tiktokbot)
print("Author: https://github.com/NoNameoN-A")
print("https://www.tiktok.com/@social_degradation_crazy/video/6898692248968400130")

"""
You can change auto value below
auto = 1 for auto views(500) OK
auto = 2 for auto hearts OK
auto = 3 for auto (FIRST) comments heart OK
auto = 4 for auto followers OK
"""
bot = 1 

driver.get("https://vipto.de/")

if bot == 1:
    loop1()
elif bot == 2:
    loop2()
elif bot == 3:
    loop3()
else:
    loop4()
`

**Comment by Zaydo123** [comment]
https://pastebin.com/vAj3RNwG

ok try replacing your code with all this. this is my custom version of the script. 
you should only have to run "pip install fake-useragent"

**Comment by h0r** [comment]
Alright, I think it's working fine. When run it asks for me to reset my Windows Defender settings for Chrome, is this necessary?. Also I'm really interested in how this thing works, would you mind explaining it to me in discord or something?

**Comment by h0r** [comment]
Also, whenever it's run it opens an empty data: page and does nothing. Is this part of the program or?

**Comment by Zaydo123** [comment]
> Also, whenever it's run it opens an empty data: page and does nothing. Is this part of the program or?

Yea, that's supposed to happen. it's just one of the quirks of using a chrome through selenium. 
if you want, hit me up, my @ is Zayd#1234 on discord.
