### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by ka1888868** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#24]
Please when I run the bot and the browser webpage opens I'm getting Cloudflare page which installed on the host website and it tells me bad gateway error. I hope if you can tell me what should I do to resolve this issue, Thanks.

**Comment by Zaydo123** [comment]
You got banned from the website, happens.

**Comment by NoNameoN-A** [comment]
> Please when I run the bot and the browser webpage opens I'm getting Cloudflare page which installed on the host website and it tells me bad gateway error. I hope if you can tell me what should I do to resolve this issue, Thanks.

Send me a photo... did you try to use a vpn?

**Comment by spinfal** [comment]
Unfortunately, that website can seemingly detect when you use a VPN, presumingly to avoid users getting around the countdown timer on their website, so a VPN might not work.

**Comment by NoNameoN-A** [comment]
# VIDEO FOR BEGINNERS - Windows aviable
If you are a beginners release a star this repository, follow me and send me a screenshot on the email alessandrogreco@hacari.org, i will send you a video where i'll show you what you must to do for solve the errors and for make it work

[Email](mailto:alessandrogreco@hacari.org)
[Repository](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot#video-for-beginners---windows-aviable)
