### ISSUE TITLE
Captcha error

### ISSUE THREAD

**Issue by finnishhacker** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#25]
Hi, no matter what i do, i get captcha error, can that be fixed?

**Comment by NoNameoN-A** [comment]
send a photo https://imgbb.com/

**Comment by finnishhacker** [comment]
nvm, there is a problem with the website where you get the views. Nothing you can do about it

**Comment by NoNameoN-A** [comment]
unfortunately i can't help you... my code is just a bot not the website... but stay tuned because it come back fast ;) now you can use the heart system
