### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by finnishhacker** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#26]
hi, new code is full of bugs. Firstly i get the tabs error which i fix with a command called autopep8, then i get an error because you have forgotten to add brackets to "Liked :D" around line 100. Then i get this third error tjhat says "raw_input" is not defined. Thats when i gave up :/

**Comment by NoNameoN-A** [comment]
For the first problem please send me the file downloaded at the email alessandrogreco@hacari.org
For the second and third problem i haven't it... did you run the program with `python Bot.py`? In python the brackets isn't necessary and raw_input works perfectly...
Please send me your file and a screenshot of the errors :)

![Image](https://i.ibb.co/5YvP8w4/output.png)

**Comment by NoNameoN-A** [comment]
IF YOU HAVE TAB ERROR RE-DOWNLOAD NOW AND USE => Bot_For_Bugged.py
