### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by Axekilo** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#28]
**Describe the error**
Inconsistent use of tabs and spaces.

**Screenshots**
![IMG_20210112_232107.jpg](https://user-images.githubusercontent.com/27922935/104419126-dd9e6780-552c-11eb-802b-892139b5767f.jpg)

**Info**
Chrome and ChromeDriver Version
Both installed.

**Comment by NoNameoN-A** [comment]
For solve this error you must send me this file.
Send me it at alessandrogreco@hacari.org
