### ISSUE TITLE
[ERROR] when i launch the file

### ISSUE THREAD

**Issue by Divin-debug** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#29]
when i launch the file with " python Bot_For_Bugged.py" i have 

`  File "Bot_For_Bugged.py", line 137
    driver = webdriver.Chrome('C:\Users\tayzers\Desktop\TikTok-Follow-Heart-Views-Bot-main\chromedriver',chrome_options=chrome_options) #Change it
                              ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
`

**Comment by NoNameoN-A** [comment]
1.
Insert `.exe` at chromedriver if you are on windows

If it will not solve
2.
Just put `r` before your normal string it converts normal string to raw string:
`driver = webdriver.Chrome(r'C:\Users\tayzers\Desktop\TikTok-Follow-Heart-Views-Bot-main\chromedriver',chrome_options=chrome_options) #Change it`

If it will not solve
3.
Change `'` with `"` so... (try with r and without)
`driver = webdriver.Chrome(r"C:\Users\tayzers\Desktop\TikTok-Follow-Heart-Views-Bot-main\chromedriver",chrome_options=chrome_options) #Change it`
