### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by im1kid** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#3]
![image](https://user-images.githubusercontent.com/74839423/100392453-d6aaac80-2ff3-11eb-9fb6-f5bf099273ff.png)

I am unable to start the bot. I have installed python, the chrome driver. I pasted in my tiktok video url and changed the bot to #3.

Can you please help me be able to start the bot.

**Comment by NoNameoN-A** [comment]
Change [this line](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot/blob/17cff9b8af2edb9c0867f507e610571ada6e56e9/TikTok-Views-Follow-Heart-Bot.py#L106) `system("clear") #If you have Windows you can use cls` and say me what do you will see

**Comment by NoNameoN-A** [comment]
did you solve?
