### ISSUE TITLE
[BUG] loop5

### ISSUE THREAD

**Issue by LeCupidity** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#30]
![image](https://user-images.githubusercontent.com/77359869/104566993-33b2fe00-5646-11eb-8e8e-ef76117552d0.png)
At the end of the code, loop5 is called, but loop5 doesn't exist

**Comment by NoNameoN-A** [comment]
[Update](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot/blob/9ffedab573e4b9b9fb59b0a8fede629bc20b31df/Bot.py#L122-L126)
