### ISSUE TITLE
Vipto.de got taken down

### ISSUE THREAD

**Issue by zitonDev** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#34]
The site vipto.de is taken down so the bot doesn't work, not sure if it's maintenance or fully taken down any idea if it will be back up in the future.

**Comment by NoNameoN-A** [comment]
# The site isn't down and the bot works
[![TikTok Bot](https://i.ibb.co/dcGXRbn/sito2.png)](https://ibb.co/z5GCz8K)

**Comment by crazyartz666** [comment]
> # The site isn't down and the bot works
> [![TikTok Bot](https://camo.githubusercontent.com/86c9dd1f70063e65d98f6bc00fe832e7007d678dbcbd36b6d0367b5cc34ab08c/68747470733a2f2f692e6962622e636f2f6463475852626e2f7369746f322e706e67)](https://ibb.co/z5GCz8K)

It is down 2

**Comment by NoNameoN-A** [comment]
The site isn't down .-.
Did you see the image? The site is on, the functions is temporarily in wait
