### ISSUE TITLE
Bad getaway [ERROR]

### ISSUE THREAD

**Issue by HomiGrotas** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#35]
After choosing an option the driver goes to a website and the code gets stuck due to a "bad getaway"

**Comment by mzooklyn** [comment]
![vipto de](https://user-images.githubusercontent.com/77994178/105764613-2ee32980-5f25-11eb-88d8-841dbd3266d3.PNG)
Same issue - site appears to be currently down,  I changed my DNS, disabled VPN, turned off firewall.  Still getting error 502 bad gateway error.

**Comment by mzooklyn** [comment]
So it does not work in windows, but works in linux.  Is there a fix?  Do you have a linux install guide ?

**Comment by NoNameoN-A** [comment]
# Vipto.de use a redirect to ketuy.com and it work perfectly in linux and in windows
![WebSite](https://i.ibb.co/d52gfPp/asd.png)

**Comment by WORSHIP2022** [comment]
ketuy.com  gives same error

**Comment by NoNameoN-A** [comment]
> ketuy.com gives same error

We are trying to understand what is the error in this issue https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot/issues/48

**Comment by WORSHIP2022** [comment]
Both sites are down. Ketuy.com and vipto.de. suggesting something is wrong
on our end is ridiculous frankly.
