### ISSUE TITLE
[BUG] When launching the bot

### ISSUE THREAD

**Issue by peekaboo77** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#36]
So i had this issue when launching the Bot 
I don’t know much about python, so if anyone knows please help me. Maybe it’s just a command to write
![979CB539-64BA-4877-9914-32DEA765C49A](https://user-images.githubusercontent.com/77738116/106039607-980b9e00-60d9-11eb-87cd-8152b4c9fa69.jpeg)
 or something super easy Thank you.

**Comment by peekaboo77** [comment]
By the way i use ISH on iphone

**Comment by NoNameoN-A** [comment]
# VIDEO FOR BEGINNERS - Windows aviable
If you are a beginners release a star this repository, follow me and send me a screenshot on the email alessandrogreco@hacari.org, i will send you a video where i'll show you what you must to do for solve the errors and for make it work

[Email](mailto:alessandrogreco@hacari.org)
[Repository](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot#video-for-beginners---windows-aviable)
