### ISSUE TITLE
[ERROR] Help

### ISSUE THREAD

**Issue by Monstermr** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#39]
![unknown](https://user-images.githubusercontent.com/44266490/106393916-c6a3b480-640a-11eb-86e2-f157f646382d.PNG)
I'm getting this error, can you help?

**Comment by Monstermr** [comment]
vipto.de
Host
Error

**Comment by NoNameoN-A** [comment]
# VIDEO FOR BEGINNERS - Windows aviable
If you are a beginners release a star this repository, follow me and send me a screenshot on the email alessandrogreco@hacari.org, i will send you a video where i'll show you what you must to do for solve the errors and for make it work

[Email](mailto:alessandrogreco@hacari.org)
[Repository](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot#video-for-beginners---windows-aviable)
