### ISSUE TITLE
Can open it on windows? If so, pls help me it closes inmediatly

### ISSUE THREAD

**Issue by MavezZ** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#41]

**Comment by NoNameoN-A** [comment]
# VIDEO FOR BEGINNERS - Windows aviable
If you are a beginners release a star this repository, follow me and send me a screenshot on the email alessandrogreco@hacari.org, i will send you a video where i'll show you what you must to do for solve the errors and for make it work

[Email](mailto:alessandrogreco@hacari.org)
[Repository](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot#video-for-beginners---windows-aviable)
