### ISSUE TITLE
[ERROR] DevTools listening...Bluetooth: bluetooth_adapter_winrt...

### ISSUE THREAD

**Issue by BSQChronicles** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#43]
Quando faccio partire lo script ricevo questi due warning/error:
DevTools listening on ws://127.0.0.1:52700/devtools/browser/8734daa8-8766-4e20-9af4-12b1f0154d07
[6348:6924:0213/103626.734:ERROR:device_event_log_impl.cc(211)] [10:36:26.734] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: Un dispositivo collegato al sistema non Þ in funzione. (0x1F)
[6348:6924:0213/103626.739:ERROR:device_event_log_impl.cc(211)] [10:36:26.738] Bluetooth: bluetooth_adapter_winrt.cc:1072 Getting Default Adapter failed.

Il chromedriven fa partire il sito ma non risolve e seleziona la funziona automaticamente, devo fare manualmente compreso inserire il link del video, normale o bug?

ChromeDriver V: 88

**Comment by NoNameoN-A** [comment]
Ciao! Grazie per aver creato una issue in modo tale da aiutare anche altre persone.
Quando lo fai partira procede correttamente e ti da solo i warning oppure si blocca proprio finché non fai qualcosa tu?

_Ovviamente non metto in conto il re-captcha... quello lo devi fare sempre manualmente ma per l'appunto dovrebbe essere l'unica cosa necessaria_

**Comment by BSQChronicles** [comment]
Ciao, grazie per la risposta così immediata,
una volta aperta la pagina di chrome con il captcha ed inserito, me reinderizza nella selezione delle funzioni (followers, hearts, ecc..)
In questo momento nella console appaiono gli errori che ho elencato nel messaggio sopra e pare non fare più nulla, versione errata di selenium magari?

**Comment by NoNameoN-A** [comment]
Guarda il warning che ti da sembrerebbe dovuto a qualche dispositivo collegato... Strano...
La versione di selenium basta che sia l'ultima e non dovrebbero esserci problemi.
Prova magari a controlalre che la versione di chromedriver sia esattametne uguale a quella di Chrome... dopo diché sinceramente non mi è mai capitato roba del genere...

Tu comunque fai un update(Aggioranmento) di tutto e poi scrivimi le versioni di ogni cosa

**Comment by BSQChronicles** [comment]
Ciao, ho aggiornato tutto ma nada, stessa situazione,
ti scrivo le versioni:

PIP: 21.0.1
Python: 3.9
ChromeDriven: 88 / Chrome: 88
Selenium: 3.141.0

**Comment by NoNameoN-A** [comment]
Il problema potrebbe essere dovuto a selenium, in tanti avete avuto problemi "strani" non appena saprò qualcosa creerò un nuovo commento, nel frattempo lascerò aperta questa issue in maniera tale da dare agli altri la possibilità di aiutarti.

If somebody have the same error please write here your files version, or if you have solved please release your solution.
Thanks :)

**Comment by NoNameoN-A** [comment]
@BSQChronicles verifica che dentro gli indirizzi PATH sia tutto collegato bene

**Comment by BSQChronicles** [comment]
Non ho risolto il problema :(

**Comment by hahalolxdxd** [comment]
I have the same error, I do not know how to fix it

**Comment by NoNameoN-A** [comment]
The problem come from some thing wrong in your path, however try with new files
