### ISSUE TITLE
Vipto.de website has 502 Error [ERROR]

### ISSUE THREAD

**Issue by PseudoDevs** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#46]
**Describe the error**
When I run the script it runs correctly but the vipto.de website is currently down.

1. Run the script
2. Wait for the website to load
3. See error

**Screenshot**
![image](https://user-images.githubusercontent.com/28098260/108580593-1967f080-7367-11eb-8837-193fde864030.png)

**Info**
Chrome and ChromeDriver Version
Same version on Chromedriver 88

**Comment by NoNameoN-A** [comment]
the website is correctly online and works good, this problem come from your connection

**Comment by Devon-Stubb** [comment]
It shows the same thing for me.

**Comment by syhrte** [comment]
> the website is correctly online and works good, this problem come from your connection

I have the same problem. host error

**Comment by NoNameoN-A** [comment]
> It shows the same thing for me.



> > the website is correctly online and works good, this problem come from your connection
> 
> I have the same problem. host error

Are you using too ethernet connection?

**Comment by Devon-Stubb** [comment]
No I'm using wireless connection

**Comment by Godwhitelight** [comment]
same problem
i am using good ethernet connection 900mbps download 120 upload
help me please.

**Comment by NoNameoN-A** [comment]
if you go to vipto.de with Chrome do you have the same problem?

**Comment by Devon-Stubb** [comment]
Yes I do.

**Comment by NoNameoN-A** [comment]
> Yes I do.

then the problem isn't went from my bot, for understand if the problem is your connection or your device, please try to go to vipto.de with some other device that is connected with the same connection, then say me if you have the same problem.
If yes so the problem is the connection, else is your pc.

**Comment by WORSHIP2022** [comment]
same problem. site is down

**Comment by NoNameoN-A** [comment]
> > Yes I do.
> 
> then the problem isn't went from my bot, for understand if the problem is your connection or your device, please try to go to vipto.de with some other device that is connected with the same connection, then say me if you have the same problem.
> If yes so the problem is the connection, else is your pc.

@Devon-Stubb pls respond

**Comment by Godwhitelight** [comment]
i tryed from all my devices, diffrent enternet , VPN, everyting
the site is down.

**Comment by NoNameoN-A** [comment]
> i tryed from all my devices, diffrent enternet , VPN, everyting
> the site is down.

If you use VPN is normal that is down, don't use VPN then try again

**Comment by WORSHIP2022** [comment]
The site is down lol. Good lord..

**Comment by NoNameoN-A** [comment]
The site is NOT( N    O    T) down.
The bot works perfectly https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot#the-bot-work-perfectly

**Comment by PseudoDevs** [comment]
> if you go to vipto.de with Chrome do you have the same problem?

M. Edge , Chrome , Opera GX, Opera Touch I got the same issue for 502 gateway 

vipto.de , zefoy.com 

![image](https://user-images.githubusercontent.com/28098260/110268335-736de480-7ffc-11eb-8d7a-53cf45801ce0.png)

![image](https://user-images.githubusercontent.com/28098260/110268394-88e30e80-7ffc-11eb-91c6-3cd758814bde.png)

May I suggest to create a non SSL website version of it so we can try from that site. I think there's a problem with the cloudflare from other internet providers that's why we encountered this gateway problem.

**Comment by NoNameoN-A** [comment]
> > if you go to vipto.de with Chrome do you have the same problem?
> 
> M. Edge , Chrome , Opera GX, Opera Touch I got the same issue for 502 gateway
> 
> vipto.de , zefoy.com
> 
> ![image](https://user-images.githubusercontent.com/28098260/110268335-736de480-7ffc-11eb-8d7a-53cf45801ce0.png)
> 
> ![image](https://user-images.githubusercontent.com/28098260/110268394-88e30e80-7ffc-11eb-91c6-3cd758814bde.png)
> 
> May I suggest to create a non SSL website version of it so we can try from that site. I think there's a problem with the cloudflare from other internet providers that's why we encountered this gateway problem.

1) you must use google chrome
2) try using a wireless connection
3) don't use vpn
4) try changing your proxy server and if you don't use one, use google service

**Comment by PseudoDevs** [comment]
I tried all methods I know. 
Mobile and Desktop also Dual boot on Linux 

![image](https://user-images.githubusercontent.com/28098260/110721267-259aeb80-824b-11eb-88a1-61dc53df3bbb.png)
![image](https://user-images.githubusercontent.com/28098260/110721282-2d5a9000-824b-11eb-8f4a-dbc9a02959e6.png)

but still also on zefoy I encountered this and other alternatives of this websites.

**Comment by hahalolxdxd** [comment]
@PseudoDevs What are the other alternatives of this website?

**Comment by PseudoDevs** [comment]
> @PseudoDevs What are the other alternatives of this website?

https://homedecoratione.com
https://zefoy.com

**Comment by NoNameoN-A** [comment]
> I tried all methods I know.
> Mobile and Desktop also Dual boot on Linux
> 
> ![image](https://user-images.githubusercontent.com/28098260/110721267-259aeb80-824b-11eb-88a1-61dc53df3bbb.png)
> ![image](https://user-images.githubusercontent.com/28098260/110721282-2d5a9000-824b-11eb-8f4a-dbc9a02959e6.png)
> 
> but still also on zefoy I encountered this and other alternatives of this websites.

# THIS IS TOTALY FALSE
# UPDATE 07/Mar/2021 -> I'm from Italy
![Bot](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot/blob/main/screenshot2.png)

# THE SITE ISN'T DOWN

**Comment by Godwhitelight** [comment]
YES IT IS


‫בתאריך יום ה׳, 25 בפבר׳ 2021 ב-6:36 מאת ‪Devon-Stubb‬‏ <‪
***@***.***‬‏>:‬

**Comment by bootyislife** [comment]
Down for me
