### ISSUE TITLE
[ERROR]TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by ouiscottebi** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#47]
**Describe the error**

  File "C:\Users\Johann\bot.py", line 25
    sleep (10)
TabError: inconsistent use of tabs and spaces in indentation

**Comment by NoNameoN-A** [comment]
If you are a beginners release a star this repository, follow me and send me a screenshot on the email alessandrogreco@hacari.org, i will send you a video where i'll show you what you must to do for solve the errors and for make it work.
