### ISSUE TITLE
I don't know anything about phyton

### ISSUE THREAD

**Issue by TamalDulce** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#5]
Hello bro, can you help me with the bot? Since I don't know anything about phyton and I can't install the chromedriver, I don't know if you can do a tutorial on how to download phyton, put selenium and install the chrome dirvers, please, you I'd be really grateful

**Comment by NoNameoN-A** [comment]
1) If you have Windows you can download Python [here](https://www.python.org/downloads/)
2) When you did, install Google Chrome [here](https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwjfr7ab3a7tAhWQ6HcKHXNhALAYABABGgJlZg&ohost=www.google.com&cid=CAESPuD2PtBToHuBNnz4fESL3xdKVdC3061Qun8Os1TBOxQ6atPFQ6GNcL-kYcy5PlcR7ubGfZ6mRZPgLUoUzXjD&sig=AOD64_06AQWS5QLSRMmnbjzok-yHjMrHOQ&q=&ved=2ahUKEwiUqK2b3a7tAhUhsKQKHdSwB8UQqyQoAHoECBcQEw&adurl=) (obviously if you don't have it)
3) See your Chrome version, and if you don't know how to find this information you can read [this article](https://www.businessinsider.com/what-version-of-google-chrome-do-i-have#:~:text=You%20can%20find%20which%20version,you%20have%20any%20updates%20available.)
4) Download ChromeDriver [here](https://chromedriver.chromium.org/downloads) with your same GoogleChrome version, so now 87...
5) Install `pip` and if you don't know how to download it you can go [here](https://phoenixnap.com/kb/install-pip-windows)  and scroll down
6) Now you can install `Selenium` with pip command, you can find a guide [here](https://selenium-python.readthedocs.io/installation.html)

Now I think that you have all that you need, however you can comment if you have else problem.
!Remember -> You must change [this lines](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot#usage)

If I helped you release a star on the repo and fork (:

!Important -> Say me if you solve or not

**Comment by fidamengalbaloch** [comment]
Plz make a video  sir  🙄🙄🙄

**Comment by TomGalla11** [comment]
For what is the bugged bot and for what is the bot file? Which should I use?

**Comment by rancak123** [comment]
Video tutorial

**Comment by BMax-sudo** [comment]
> 
> 
> Plz make a video sir 🙄🙄🙄

If you don't have at least some knowdelege of following instructions or how python works or anything, you should learn that before trying to do anything on GitHub. He even linked guides for you, it couldn't be sipler, really

**Comment by NoNameoN-A** [comment]
# VIDEO FOR BEGINNERS - Windows aviable
If you are a beginners release a star this repository, follow me and send me a screenshot on the email alessandrogreco@hacari.org, i will send you a video where i'll show you what you must to do for solve the errors and for make it work

[Email](mailto:alessandrogreco@hacari.org)
[Repository](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot#video-for-beginners---windows-aviable)

**Comment by Pavle20** [comment]
Hi, can you please help me I got this massage Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home because I don't know where is my chromdriver path and I have another problem my chrome version is Version 88.0.4324.96 and I can't find the same driver on that web site.

**Comment by fidamengalbaloch** [comment]
😘😘😘😘

**Comment by WafflesGaming** [comment]
when i open the bot.py it closes instantly

**Comment by Frozsty21** [comment]
hey im getting an error saying" line 25
    sleep(10)
TabError: inconsistent use of tabs and spaces in indentation"
how do i fix?

**Comment by NoNameoN-A** [comment]
@Pavle20 @Frozsty21 

# VIDEO FOR BEGINNERS - Windows aviable
If you are a beginners release a star this repository, follow me and send me a screenshot on the email alessandrogreco@hacari.org, i will send you a video where i'll show you what you must to do for solve the errors and for make it work

[Email](mailto:alessandrogreco@hacari.org)
[Repository](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot#video-for-beginners---windows-aviable)
