### ISSUE TITLE
[BUG] Cant do it "module not install selenium"

### ISSUE THREAD

**Issue by 3raden** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#50]
**Describe the bug**

**To Reproduce**
![image](https://user-images.githubusercontent.com/64098772/111057376-b12f9a80-844c-11eb-9f79-66d1f42c1f00.png)

**Expected behavior**

**Screenshots**

**Info**
Chrome and ChromeDriver Version

**Additional context**

**Comment by NoNameoN-A** [comment]
Hi try with
`sudo pip3 install selenium`
