### ISSUE TITLE
[ERROR] When i open the thing it just closes

### ISSUE THREAD

**Issue by IsaacBarazani** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#52]
**Describe the error** Hi, Im new and i don't know what to do :((
A clear and concise description of what the error is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info**
Chrome and ChromeDriver Version

**Additional context**

**Comment by NoNameoN-A** [comment]
Hi can you send some screenshots?

Do you have downloaded chrodriver with a version equals to your Chrome?
Do you have some errors?

If you are a beginners release a star this repository, follow me and send me a screenshot on the email alessandrogreco@hacari.org, i will send you a video where i'll show you what you must to do for solve the errors and for make it work.
