### ISSUE TITLE
 version is 89.0.4389.82 Error

### ISSUE THREAD

**Issue by DrDinos** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#53]
When ever i try to run the bot i get this msg
https://prnt.sc/10o0uol
i tried installing ver.90 but still its not working idk why

**Comment by NoNameoN-A** [comment]
Hi Dinos, what is your chromedriver version? is equals to your chrome version?

**Comment by DrDinos** [comment]
i figured it out but now im getting this error 
You didn't solve the captcha yet. Need to refresh to avoid endless loop.

**Comment by DrDinos** [comment]
Wait i saw your issue on how to fix them 
Thanks alot for this 
Thanks you for this amazing project

**Comment by NoNameoN-A** [comment]
@DrDinos Your Welcome ;)
Remember to follow me on GitHub and release a star on the repository :D
Good Day ;)
