### ISSUE TITLE
[ERROR] You didn't solve the captcha yet. Need to refresh to avoid endless loop.

### ISSUE THREAD

**Issue by Vap3rWave** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#54]
**Describe the error**
Trying to run views and it keeps printing "You didn't solve the captcha yet. Need to refresh to avoid endless loop."

**To Reproduce**
1. Go to 'dir of bot'
2. 'running Bot.py'
3. replaced line 130 with link to video
4. When running Bot.py it constantly refreshes a cloudfare page with no video and prints out "You didn't solve the captcha yet. Need to refresh to avoid endless loop." in console and the website that it pulled up is this = https://imgur.com/a/uIDzuOs

**Expected behavior**
Supposed to say "Views success delivered! Total 500 views"

**Screenshots**
https://imgur.com/a/uIDzuOs

**Info**
Chrome and ChromeDriver Version
Chrome : Version 89.0.4389.90 
ChromeDriver: ChromeDriver 89.0.4389.23

**Additional context**
There is reference to use python Bot_For_Bugged.py I do not have this file, where can I find it?

**Comment by NoNameoN-A** [comment]
https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot/issues/46
