### ISSUE TITLE
Vipto.de website has 502 Error[ERROR]

### ISSUE THREAD

**Issue by devins-07** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#58]
![Screenshot (27)](https://user-images.githubusercontent.com/80927794/111843032-d30aa080-88d6-11eb-858a-7a068f89427e.png)

Vipto.de website has 502 Error 

502 error i am wondering if there is a certain proxy sever i should use.

**Comment by NoNameoN-A** [comment]
https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot/issues/46
