### ISSUE TITLE
[ERROR] Errors on line 73, 71, 45

### ISSUE THREAD

**Issue by fdvfkjvd4354** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#60]
**Describe the error**
A clear and concise description of what the error is.

**To Reproduce**
1. Go to 'tiktok folder bot'
2. Click on 'bot.py'
3. Scroll down to any number'
4. See error tool closes.

**Expected behavior**
It should launch the webpage but doesn't

**Screenshots**

**Info**
Chrome version 89.0.4389.90 and ChromeDriver Version 89.0.4389.23

**Additional context**
all works well, i check the errors by CMD it says theirs errors on line 73, 71, 45. Idk what to do. If i launch bot.py and press any number it closes. No webpage opening like in the video.

**Comment by NoNameoN-A** [comment]
If you are a beginners release a star this repository, follow me and send me a screenshot on the email alessandrogreco@hacari.org, i will send you a video where i'll show you what you must to do for solve the errors and for make it work.
