### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by Akash123454** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#61]
Ciao! 
Scusa se scrivo in italiano, il mio errore è nel terminale quando attivo il bot utilizzando: Python Bot.py. 
Mi risultano effettivamente tutt'e 4 le stringhe del bot di riferimento.
Ma quando vado a cliccare, ad esempio, la numero 1 delle richieste, mi risulta questo errore: 

/Users/xxxx/Desktop/Bot.py:151: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=r'/home/nonameon/Scaricati/TikTok-Follow-Heart-Views-Bot-main/chromedriver',chrome_options=chrome_options) #Change it
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nonameon/Scaricati/TikTok-Follow-Heart-Views-Bot-main/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/giusy/Desktop/Bot.py", line 151, in <module>
    driver = webdriver.Chrome(executable_path=r'/home/nonameon/Scaricati/TikTok-Follow-Heart-Views-Bot-main/chromedriver',chrome_options=chrome_options) #Change it
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Come posso risolverlo?

**Comment by NoNameoN-A** [comment]
Qua devi cambiare con il path del tuo chromedriver, se usi windows metti .exe
```
File "/Users/giusy/Desktop/Bot.py", line 151, in
driver = webdriver.Chrome(executable_path=r'/home/nonameon/Scaricati/TikTok-Follow-Heart-Views-Bot-main/chromedriver',chrome_options=chrome_options) **#Change it**
```

Prova a lanciarlo con `python3 Bot.py` e sopratutto usando gli ultimi files non quelli vecchi.

Infine ricorda che se vuoi puoi diventare [sponsor](https://github.com/sponsors/NoNameoN-A) con un solo dollaro [qui](https://github.com/sponsors/NoNameoN-A) -> https://github.com/sponsors/NoNameoN-A

Oppure semplicemente seguirmi e lasciare una Star alla repository per supportarmi gratuitamente :)

**Comment by Akash123454** [comment]
Ciao, ho un Mac!
Ora ho questo errore

/Users/Jhkio/Desktop/Bot.py:151: DeprecationWarning: use options instead of
chrome_options

driver =
webdriver.Chrome(executable_path=r'/home/nonameon/Scaricati/TikTok-Follow-Heart-Views-Bot-main/chromedriver',chrome_options=chrome_options)
#Change it
Traceback (most recent call last):
File
"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py",
line 72, in start
self.process = subprocess.Popen(cmd, env=self.env,
File
"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py",
line 951, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File
"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py",
line 1823, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory:
'/home/nonameon/Scaricati/TikTok-Follow-Heart-Views-Bot-main/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/Jhkio/Desktop/Bot.py", line 151, in
driver =
webdriver.Chrome(executable_path=r'/home/nonameon/Scaricati/TikTok-Follow-Heart-Views-Bot-main/chromedriver',chrome_options=chrome_options)
#Change it
File
"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py",
line 73, in init
self.service.start()
File
"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py",
line 81, in start
raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver'
executable needs to be in PATH. Please see
https://sites.google.com/a/chromium.org/chromedriver/home

Il giorno lun 22 mar 2021 alle 08:35 Alessandro ***@***.***>
ha scritto:

**Comment by NoNameoN-A** [comment]
**Qua devi cambiare con il path del tuo chromedriver, se usi windows metti .exe**
```
File "/Users/giusy/Desktop/Bot.py", line 151, in
driver = webdriver.Chrome(executable_path=r'/home/nonameon/Scaricati/TikTok-Follow-Heart-Views-Bot-main/chromedriver',chrome_options=chrome_options) #Change it
```

**Comment by Akash123454** [comment]
Quindi al posto di questo File "/Users/giusy/Desktop/Bot.py", line 151, in
driver = webdriver.Chrome(executable_path=r'/home/nonameon/
Scaricati/TikTok-Follow-Heart-Views-Bot-main/chromedriver',chrome_options=chrome_options)
#Change it

inserisco
/usr/local/bin ?

Il giorno lun 22 mar 2021 alle 12:09 Alessandro ***@***.***>
ha scritto:

**Comment by NoNameoN-A** [comment]
Il percordo `/home/nonameon/Scaricati/TikTok-Follow-Heart-Views-Bot-main/chromedriver` rappresenta il percorso/path del file "chromedriver" sul mio computer.
Ciò vuol dire che il file "chromedriver" sul mio computer è nella cartella `/home/nonameon/Scaricati/TikTok-Follow-Heart-Views-Bot-main/`.
Se tu vai nella cartella sul tuo computer dove hai "chromedriver" allora potrai sapere qual'è il percorso/path.

detto ciò

Al posto della riga
`driver = webdriver.Chrome(executable_path=r'/home/nonameon/Scaricati/TikTok-Follow-Heart-Views-Bot-main/chromedriver',chrome_options=chrome_options)`
qual'ora il tuo percorso fosse **ad esempio** /home/akash/documenti/cartella-con-dentro-chromedriver/ allora dovresti scrivere questa cosa qui
`driver = webdriver.Chrome(executable_path=r'/home/akash/documenti/cartella-con-dentro-chromedriver/chromedriver',chrome_options=chrome_options)`
ponendo "chromedriver" indicando quindi "chromedriver" programma e non cartella

N.B. non so se con MacOS cambia qualcosa ma questa è una definizione funzionante relativa a Linux e Windows ma penso vada bene anche per MacOS visto che si basa su linux.

**Comment by Akash123454** [comment]
Ho fatto quel che mi hai chiesto e mi dà questo nuovo errore. Ti ho
sottolineato in blu quel che ho modificato

Il giorno lun 22 mar 2021 alle 14:27 Alessandro ***@***.***>
ha scritto:

**Comment by NoNameoN-A** [comment]
contattami tramite email mandandomi uno screenshot alessandrogreco@hacari.org

**Comment by Akash123454** [comment]
Amico, tutto a posto!
Grazie mille

Il giorno lun 22 mar 2021 alle 14:37 Alessandro ***@***.***>
ha scritto:
