### ISSUE TITLE
[ERROR] ChromeDriver executable needs to be in PATH

### ISSUE THREAD

**Issue by thatonedudedudelol** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#63]
When i type python bot.py it lets me pick what i eant but when i do it says a bunch of random stuff and then says 

WebDriverException: Message: 'chromedriver' executable needs to be in PATH. 

Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by NoNameoN-A** [comment]
Did you change chromedriver path in the Bot.py file? watch 139 line

Remember to insert your chromedriver in your bot directory

run with python3 Bot.py

**Comment by thatonedudedudelol** [comment]
Can you like tell me how to because I'm confused what you mean

**Comment by Petr2282** [comment]
Man you need just add R like PATH = r’path’

**Comment by thatonedudedudelol** [comment]
Oh okay. I'm new to linux so I was not sure
