### ISSUE TITLE
I keep getting "ModuleNotFoundError: No module named 'selenium"

### ISSUE THREAD

**Issue by 0reo1** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#69]
I'm pretty sure I have everything else setup correctly but whenever I try and run it I keep getting this same error

**Comment by NoNameoN-A** [comment]
pip install selenium

**Comment by kiven7e** [comment]
i am having the same problem and when i run `pip install selenium` i get
`kiven@linux:~/Desktop/tik-tok$ pip install selenium
Requirement already satisfied: selenium in /home/kiven/.local/lib/python3.9/site-packages (3.141.0)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from selenium) (1.26.4)
`

**Comment by kiven7e** [comment]
> pip install selenium

i am having the same problem and when i run `pip install selenium` i get
`kiven@linux:~/Desktop/tik-tok$ pip install selenium
Requirement already satisfied: selenium in /home/kiven/.local/lib/python3.9/site-packages (3.141.0)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from selenium) (1.26.4)
`
