### ISSUE TITLE
[ERROR] ...solve the captcha...

### ISSUE THREAD

**Issue by NoNameoN-A** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#71]
![image](https://user-images.githubusercontent.com/16680751/113818783-e5c41700-97aa-11eb-84ad-86384950836f.png)

_Originally posted by @Mr-ZNN in https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot/issues/65#issuecomment-814631096_

**Comment by NoNameoN-A** [comment]
@Mr-ZNN Did you insert the captcha?

**Comment by Mr-ZNN** [comment]
How to insert the captcha?

**Comment by NoNameoN-A** [comment]
lol

**Comment by metsakast** [comment]
![image](https://user-images.githubusercontent.com/66119995/113935723-8b08da80-97ff-11eb-92eb-072fe1b30f3c.png)

**Comment by NoNameoN-A** [comment]
i don't understand @metsakast
