### ISSUE TITLE
[ERROR] No module named 'selenium'

### ISSUE THREAD

**Issue by EarningEye3** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#72]
This pops up even after installing selenium
![image](https://user-images.githubusercontent.com/78822697/114219788-66ca0c80-996b-11eb-8a9a-b75f7dd0853c.png)

**Comment by Stxtic-Makes-stuff** [comment]
email him

**Comment by NoNameoN-A** [comment]
pip install selenium
