### ISSUE TITLE
[BUG] its not working

### ISSUE THREAD

**Issue by Satanicx** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#74]
i just click on it and nothing happens (i have selenium installed with pip )

**Comment by NoNameoN-A** [comment]
did you run from terminal/cmd?

**Comment by Satanicx** [comment]
can you dm me on discord satanic#0001 its alot easier to talk there

**Comment by NoNameoN-A** [comment]
contact me at the email alessandrogreco@hacari.org for private assistance

**Comment by lahart99** [comment]
Your chrome driver is incorrect probably.
