### ISSUE TITLE
[BUG] Doesnt work on my computer, but it does on my phone

### ISSUE THREAD

**Issue by Motzumoto** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#75]
**Describe the bug**
The website "zefoy.com" works on all of my phones but it refuses to work on my pc, ive even changed my IP and even after moving to a whole different location it still wont work.
**To Reproduce**
1. Go to the website on any computer with windows10

**Expected behavior**
All the options should pop up

**Screenshots**
[Screenshot](https://zoe.is-super-sexy.xyz/82lc2l.png)

**Info**
Chrome and ChromeDriver Version
Version 89.0.4389.128 (Official Build) (64-bit)

**Additional context**
Nothing really other than it doesnt work on computers (I'm not cloning the code, im directly using the website)

Edit: This actually wont work on any browsers on my computer, but works fine with my android phone. Is there a specific reason to this?

**Comment by NoNameoN-A** [comment]
Hi try following this issue https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot/issues/65

If you don't understand what you must to do, don't worry, contact me at the email alessandrogreco@hacari.org
