### ISSUE TITLE
Error before running the program

### ISSUE THREAD

**Issue by Bubbtube** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#79]
![image](https://user-images.githubusercontent.com/83686321/117097772-f97b8280-ad42-11eb-964e-417261039e5d.png)

sup bro^^

i'm trying to run the program but i get some errors, many of them i've solved, but this one i can't even understand what it means.

this error starts when i run the program and select the option, it say something about the path of the chromedriver.

infos
chrome and chromedriver are .90
i'm using the windows 10 pro btw

(Sorry for the english... brazilian here^^)

**Comment by Bubbtube** [comment]
![image](https://user-images.githubusercontent.com/83686321/117098345-94c12780-ad44-11eb-91bf-8f506f1bb228.png)


i,ve tried using options instead of chrome_options, it onlys gets the same error but without these first 2 lines

**Comment by NoNameoN-A** [comment]
for private info contact me with email alessandrogreco@hacari.org
