### ISSUE TITLE
wont open

### ISSUE THREAD

**Issue by jazxminemasters** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#8]
hello im really new to this stuff and my problem is it wont allow me to download the chrome driver it says Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully. what do i do ?

**Comment by NoNameoN-A** [comment]
What is the problem?

**Comment by jazxminemasters** [comment]
> What is the problem?

i said it in the comment ^^ i just edited it

**Comment by NoNameoN-A** [comment]
> > What is the problem?
> 
> i said it in the comment ^^ i just edited it

What is your Chome version? Download the same version for chromedriver, so, if you have Chrome 87... then download [it ](https://chromedriver.storage.googleapis.com/index.html?path=87.0.4280.88/)

**Comment by jazxminemasters** [comment]
> > > What is the problem?
> > 
> > 
> > i said it in the comment ^^ i just edited it
> 
> What is your Chome version? Download the same version for chromedriver, so, if you have Chrome 87... then download [it ](https://chromedriver.storage.googleapis.com/index.html?path=87.0.4280.88/

i have

**Comment by jazxminemasters** [comment]
i have tried to download it but when i open the download of chrome driver it says 

Starting ChromeDriver 87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

**Comment by NoNameoN-A** [comment]
`ChromeDriver was started successfully.`
