### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by redninjaawesome** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#86]
**Describe the error**
A clear and concise description of what the error is.

**To Reproduce**
1. Go to 'The Folder'
2. Click on '.py file'
3. Scroll down to 'nothing'
4. It Crashes

**Expected behavior**

**Screenshots**

**Info**
Chrome and ChromeDriver Version
The Newest One
**Additional context**

**Comment by NoNameoN-A** [comment]
use cmd
