### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by Batke08** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#87]
tiktok like view bot just crashes every time i launched it.
Please fix it.
Please.
![Screenshot (18)](https://user-images.githubusercontent.com/61541676/122825483-879ad080-d2d1-11eb-8ac1-5b0e193af62b.png)

**Comment by NoNameoN-A** [comment]
for private assistance contact me with email alessandrogreco@hacari.org
