### ISSUE TITLE
[ERROR] https://vipto.de/ Error 502 Bad gateway

### ISSUE THREAD

**Issue by Godwhitelight** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#9]
ween the window of crome opening on  https://vipto.de/ thats saying 
![image](https://user-images.githubusercontent.com/73111474/101280019-41679f00-37cf-11eb-8c67-4a357d0774e7.png)

**Comment by NoNameoN-A** [comment]
Did you active a vpn? Your must close it...
If it doesn't work try to change your IPv4 addresses with 8.8.8.8; 8.8.4.4;

[Guide link](https://developers.google.com/speed/public-dns/docs/using) or search on Google `How to change public dns`
