### ISSUE TITLE
[ERROR] I am confident that either me or python doing something wrong

### ISSUE THREAD

**Issue by MUGnifisent** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#90]
No matter how i run it, i get this message:
"Traceback (most recent call last):
  File "C:\Users\Nitro\Desktop\TikTok-Follow-Heart-Views-Bot-main\Bot.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'"
Can you help me?

**Comment by Njemac** [comment]
**U need install selenium**

`pip install selenium`
