### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ARR4NN** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#99]
https://vipto.de/
Says Cloudflare host error

**Comment by pigeonburger** [comment]
This isn't a bug, the site is down, therefore the tool cannot work.

**Comment by pigeonburger** [comment]
When the website starts working again. This isn’t an error with the script.

**Comment by NoNameoN-A** [comment]
the website isn't down
we have solve it here https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot/issues/65

**Comment by pigeonburger** [comment]
That's exactly my point, now that the website is back up, the tool will work. It wasn't an issue with the script :)
